/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectBrief = IDL.Record({
  'projectName' : IDL.Text,
  'description' : IDL.Text,
  'goals' : IDL.Text,
  'budget' : IDL.Opt(IDL.Nat),
  'timeline' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerProjectBrief' : IDL.Func([], [IDL.Opt(ProjectBrief)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveProjectBrief' : IDL.Func([ProjectBrief], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectBrief = IDL.Record({
    'projectName' : IDL.Text,
    'description' : IDL.Text,
    'goals' : IDL.Text,
    'budget' : IDL.Opt(IDL.Nat),
    'timeline' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerProjectBrief' : IDL.Func([], [IDL.Opt(ProjectBrief)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveProjectBrief' : IDL.Func([ProjectBrief], [], []),
  });
};

export const init = ({ IDL }) => { return []; };